rm(list = ls(all=TRUE))
setwd("C:\\Users\\User\\Downloads")
task<-read.csv("train.csv",header = T)
str(task)
task<-task[,-c(1,4,9,10,11)]
summary(task)
sum(is.na(task))
library(DMwR)
task<-centralImputation(task)
str(task)
task$Survived<-as.factor(task$Survived)
task$Pclass<-as.factor(task$Pclass)
rows<-seq(1,nrow(task),1)
set.seed(123)
trainrows<-sample(rows,(70*nrow(task))/100)
traindata<-task[trainrows,]
validation<-task[-trainrows,]
model1<-glm(Survived~.,data = traindata,family = "binomial")
summary(model1)
library(MASS)
step1<-stepAIC(model1,direction = "both")
model2<-glm(Survived~.-Parch -Embarked,data = traindata,family = "binomial")
summary(model2)
step2<-stepAIC(model2)
library(car)
vif(model2)
library(ROCR)
predict1<-predict(model2,traindata ,type = 'response')
pred_class<-ifelse(predict1>0.5,1,0)
#pred_class<-as.data.frame(pred_class)
traintable<-table(pred_class,traindata$Survived)
accuracy1<-sum(diag(traintable))/sum(traintable)
print(accuracy1)
predict_val<-predict(model2,validation,type = "response")
preds_val<-ifelse(predict_val>0.5,1,0)
#preds_val<-as.data.frame(preds_val)
validtable<-table(validation$Survived,preds_val)
#confusion_matrix<-table(traindata$Survived,preds_val[,1])
accuracy2<-sum(diag(validtable))/sum(validtable)
print(accuracy2)
summary(model2)
testimport1<-read.csv("test.csv",header = T)
testimport1<-testimport1[,-c(3,8,9,10)]
testimport1$Pclass<-as.factor(testimport$Pclass)
str(testimport1)
sum(is.na(testimport1))
summary(testimport1)
testimport1<-centralImputation(testimport1)
testpred<-predict(model2,testimport1,type = "response")
survived1<-ifelse(testpred>0.5,1,0)
testimport<-cbind(testimport1$PassengerId,survived1)
testtable<-table(survived1,testimport$survived1)
accuracytest<-sum(diag(testtable))/sum(testtable)
testimport<-as.data.frame(testimport)
colnames(testimport)[which(names(testimport)=="V1")]<-"Pid"
write.csv(testimport,"devendra_sample.csv",row.names = F)
